export const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    CART_NOT_FOUND: 4,
    PRODUCT_NOT_FOUND: 5,
    AUTH_ERROR: 6,
    INVALID_JSON: 7,
    INVALID_PARAM: 8
}